import { Test, TestingModule } from '@nestjs/testing';
import { CreateUserUseCase } from './create-user.usecase';
import { UserRole } from '@/module/users/domain/interface/role.interface';
import { failure } from '@/core/common/err.utils';

describe('Create user test', () => {
  let useCase: CreateUserUseCase;
  let mockRepository: {
    create: jest.Mock<any, any, any>;
    findByEmail: jest.Mock;
    save: jest.Mock;
  };

  beforeEach(async () => {
    mockRepository = {
      create: jest.fn(),
      findByEmail: jest.fn(),
      save: jest.fn(),
    };
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        CreateUserUseCase,
        { provide: 'IUserRepository', useValue: mockRepository },
      ],
    }).compile();
    useCase = module.get<CreateUserUseCase>(CreateUserUseCase);
  });

  describe('Create new user', () => {
    it('should return new user after processing the user data', async () => {
      const newUser = {
        username: 'example',
        email: 'exampleone@user.com',
        phone: '7488399939',
        role: 'Student' as UserRole,
      };

      mockRepository.findByEmail.mockResolvedValue({ ok: true, value: null });
      mockRepository.save.mockResolvedValue({ ok: true, value: newUser });
      const result = await useCase.execute(newUser);

      expect(result.ok).toBe(true);
      if (result.ok) expect(result.value).toEqual(newUser);
    });
  });

  it('should throw error if email not provided', async () => {
    const newUser = {
      username: 'example',
      phone: '7488399939',
      role: 'Student' as UserRole,
      id: '777dhe88', // generated by crypto uuid
    };

    mockRepository.findByEmail.mockResolvedValue(
      failure({ type: 'NOT_FOUND', message: 'Email not provided' }),
    );

    const result = await useCase.execute(newUser as any);

    if (!result.ok)
      expect(result.error).toEqual({
        type: 'NOT_FOUND',
        message: 'Email not provided',
      });
  });

  it('should throw error when repository.save fails', async () => {
    const newUser = {
      username: 'example',
      email: 'exampleone@user.com',
      phone: '7488399939',
      role: 'Student' as UserRole,
    };

    mockRepository.findByEmail.mockResolvedValue({ ok: true, value: null });
    mockRepository.save.mockResolvedValue(
      failure({
        type: 'INTERNAL',
        message: 'Failed to save new user',
      }),
    );

    const result = await useCase.execute(newUser);

    if (!result.ok)
      expect(result.error).toEqual({
        type: 'INTERNAL',
        message: 'Failed to save new user',
      });
  });
});
